# Generated by Django 6.0.6 on 2026-07-02 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('permanent_fail', 'Permanent Failure'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_jobs', to='news.news')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.socialplatform')),
                ('telegram_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.telegramchannel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='posts.postjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='postjob',
            index=models.Index(fields=['status', 'platform'], name='posts_postj_status_0fdf2d_idx'),
        ),
        migrations.AddIndex(
            model_name='postjob',
            index=models.Index(fields=['next_retry_at'], name='posts_postj_next_re_aa65cf_idx'),
        ),
    ]
