# Generated by Django 6.0.6 on 2026-07-05 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('social', '0003_update_socialplatform_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='buffer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_jobs', to='social.bufferaccount'),
        ),
    ]
