# Generated by Django 6.0.2 on 2026-07-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postjob_buffer_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcurrentTaskLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100, unique=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'concurrent_task_locks',
            },
        ),
    ]
