# Generated by Django 6.0.6 on 2026-07-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=2, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsFilterRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('category', 'Category'), ('country', 'Country'), ('source', 'Source'), ('keyword', 'Keyword')], max_length=20)),
                ('rule_action', models.CharField(choices=[('include', 'Include'), ('exclude', 'Exclude')], default='include', max_length=10)),
                ('value', models.CharField(max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['rule_type', 'value'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_news_id', models.IntegerField(db_index=True, unique=True)),
                ('title', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('link', models.URLField(max_length=500)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('published', models.DateTimeField()),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('source', models.CharField(db_index=True, max_length=100)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-published'],
                'indexes': [models.Index(fields=['category', 'source'], name='news_news_categor_47cb8a_idx'), models.Index(fields=['published', 'api_news_id'], name='news_news_publish_201c86_idx')],
            },
        ),
    ]
