# Generated by Django 6.0.6 on 2026-07-10 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('social', '0006_bufferaccount_api_url_bufferaccount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='buffer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='social.bufferaccount'),
        ),
        migrations.AlterField(
            model_name='news',
            name='api_news_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='news',
            unique_together={('buffer_account', 'api_news_id')},
        ),
    ]
