# Generated by Django 6.0.6 on 2026-07-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('twitter', 'X (Twitter)'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('telegram', 'Telegram')], max_length=20, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the channel', max_length=100)),
                ('channel_username', models.CharField(help_text='@username of the channel', max_length=50, unique=True)),
                ('channel_chat_id', models.CharField(help_text='Numeric chat ID (negative for channels)', max_length=50, unique=True)),
                ('bot_token', models.CharField(help_text='Bot token from @BotFather', max_length=150)),
                ('bot_username', models.CharField(blank=True, help_text="Bot's username", max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Set to True after successful test')),
                ('default_hashtags', models.CharField(blank=True, help_text='Default hashtags to append to posts', max_length=200)),
                ('parse_mode', models.CharField(choices=[('HTML', 'HTML'), ('Markdown', 'Markdown')], default='HTML', max_length=20)),
                ('subscriber_count', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
