# Generated by Codex on 2026-07-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_bufferaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialplatform',
            name='name',
            field=models.CharField(
                choices=[
                    ('telegram', 'Telegram'),
                    ('buffer', 'Buffer'),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
