# Generated by Django 6.0.6 on 2026-07-05 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_update_socialplatform_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bufferaccount',
            old_name='access_token',
            new_name='api_key',
        ),
        migrations.RemoveField(
            model_name='bufferaccount',
            name='refresh_token',
        ),
    ]
