# Generated by Django 6.0.6 on 2026-07-05 14:35

from django.db import migrations


def seed_socialplatform_rows(apps, schema_editor):
    SocialPlatform = apps.get_model('social', 'SocialPlatform')
    for name in ('telegram', 'buffer'):
        SocialPlatform.objects.get_or_create(
            name=name,
            defaults={'enabled': False},
        )


def reverse_seed_socialplatform_rows(apps, schema_editor):
    SocialPlatform = apps.get_model('social', 'SocialPlatform')
    SocialPlatform.objects.filter(name__in=('telegram', 'buffer')).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_rename_access_token_to_api_key'),
    ]

    operations = [
        migrations.RunPython(
            seed_socialplatform_rows,
            reverse_seed_socialplatform_rows,
        ),
    ]
