# Generated by Django 6.0.6 on 2026-07-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_seed_socialplatform_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='bufferaccount',
            name='api_url',
            field=models.URLField(default='https://ubuntureport.onrender.com/api/news/top-sources-recent/', help_text='Upstream API URL to fetch news from for this account', max_length=500),
        ),
        migrations.AddField(
            model_name='bufferaccount',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Display name for this account (shown in sidebar)', max_length=200),
        ),
    ]
